// Generated by CIRCT firtool-1.149.0
module Axi4Lite32Cmd(
  input         clock,
                reset,
  input  [31:0] S_AXI_awaddr,
  input         S_AXI_awvalid,
  output        S_AXI_awready,
  input  [31:0] S_AXI_wdata,
  input  [3:0]  S_AXI_wstrb,
  input         S_AXI_wvalid,
  output        S_AXI_wready,
  output [1:0]  S_AXI_bresp,
  output        S_AXI_bvalid,
  input         S_AXI_bready,
  input  [31:0] S_AXI_araddr,
  input         S_AXI_arvalid,
  output        S_AXI_arready,
  output [31:0] S_AXI_rdata,
  output [1:0]  S_AXI_rresp,
  output        S_AXI_rvalid,
  input         S_AXI_rready
);

  wire [31:0] _dut_out;
  reg         softResetReg;
  reg         softResetDoneReg;
  reg  [2:0]  resetCounterReg;
  reg         awHoldValidReg;
  reg  [31:0] awHoldAddrReg;
  reg         wHoldValidReg;
  reg  [31:0] wHoldDataReg;
  reg  [3:0]  wHoldStrbReg;
  reg         bvalidReg;
  reg  [1:0]  brespReg;
  wire        S_AXI_awready_0 = ~awHoldValidReg & ~bvalidReg;
  wire        S_AXI_wready_0 = ~wHoldValidReg & ~bvalidReg;
  wire        doWrite = awHoldValidReg & wHoldValidReg & ~bvalidReg;
  wire        _GEN = wHoldStrbReg != 4'hF;
  wire        _GEN_0 = awHoldAddrReg == 32'h0;
  wire        _GEN_1 = awHoldAddrReg == 32'h30;
  wire        _GEN_2 = _GEN | _GEN_0;
  reg  [31:0] rdataReg;
  reg         rstateReg;
  wire        arFire_layerCapture = S_AXI_arvalid & ~rstateReg;
  wire [19:0] araddr_layerCapture = S_AXI_araddr[19:0];
  wire        _layerCapture = |araddr_layerCapture;
  wire        _GEN_3 = ~doWrite | _GEN | ~_GEN_0;
  wire        awFire = S_AXI_awvalid & S_AXI_awready_0;
  wire        wFire = S_AXI_wvalid & S_AXI_wready_0;
  always @(posedge clock) begin
    if (reset) begin
      softResetReg <= 1'h0;
      softResetDoneReg <= 1'h0;
      resetCounterReg <= 3'h0;
      awHoldValidReg <= 1'h0;
      wHoldValidReg <= 1'h0;
      bvalidReg <= 1'h0;
      brespReg <= 2'h0;
      rstateReg <= 1'h0;
    end
    else begin
      softResetReg <= doWrite & ~_GEN & _GEN_0 | (|resetCounterReg) & softResetReg;
      softResetDoneReg <= _GEN_3 & (~(|resetCounterReg) | softResetDoneReg);
      if (_GEN_3) begin
        if (|resetCounterReg)
          resetCounterReg <= resetCounterReg - 3'h1;
      end
      else
        resetCounterReg <= 3'h0;
      awHoldValidReg <= ~doWrite & (awFire | awHoldValidReg);
      wHoldValidReg <= ~doWrite & (wFire | wHoldValidReg);
      bvalidReg <= ~(bvalidReg & S_AXI_bready) & (doWrite | bvalidReg);
      if (doWrite)
        brespReg <= {_GEN, 1'h0};
      rstateReg <= ~(rstateReg & S_AXI_rready) & (arFire_layerCapture | rstateReg);
    end
    if (awFire)
      awHoldAddrReg <= {12'h0, S_AXI_awaddr[19:0]};
    if (wFire) begin
      wHoldDataReg <= S_AXI_wdata;
      wHoldStrbReg <= S_AXI_wstrb;
    end
    if (arFire_layerCapture)
      rdataReg <=
        araddr_layerCapture == 20'h10
          ? 32'hDEADBEEF
          : araddr_layerCapture == 20'h20
              ? 32'h1A706279
              : _layerCapture
                  ? (araddr_layerCapture == 20'h30
                       ? _dut_out
                       : S_AXI_araddr | 32'hBAD00000)
                  : {31'h0, softResetDoneReg};
  end // always @(posedge)
  Dut #(
    .BW(32)
  ) dut (
    .clock (clock),
    .reset (softResetReg | reset),
    .in    (~doWrite | _GEN_2 | ~_GEN_1 ? 32'h0 : wHoldDataReg),
    .valid (doWrite & ~_GEN_2 & _GEN_1),
    .out   (_dut_out)
  );
  assign S_AXI_awready = S_AXI_awready_0;
  assign S_AXI_wready = S_AXI_wready_0;
  assign S_AXI_bresp = brespReg;
  assign S_AXI_bvalid = bvalidReg;
  assign S_AXI_arready = ~rstateReg;
  assign S_AXI_rdata = rdataReg;
  assign S_AXI_rresp = 2'h0;
  assign S_AXI_rvalid = rstateReg;
endmodule

